[package]
name = "iouring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = "0.6.0"
libc = "0.2.147"
page_size = "0.5.0"
slab = "0.4.8"
