on: [push, pull_request]

name: CI - C

jobs:
  build_iouring:
    name: Build io_uring
    runs-on: ubuntu-latest
    steps:
      - name: Install system deps
        run: apt update && apt install liburing-dev

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Compile iouring
        working-directory: src/iouring/c
        run: make
